// Code generated by go-swagger; DO NOT EDIT.

// Package restapi backend
//
//  backend
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 0.0.0
//
//  Consumes:
//    - multipart/form-data
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
