// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "backend",
    "title": "backend",
    "version": "0.0.0"
  },
  "paths": {
    "/notify": {
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "responses": {
          "200": {
            "description": "Deployment scheduled."
          },
          "500": {
            "description": "Server error."
          }
        }
      }
    },
    "/payed": {
      "post": {
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "text/plain"
        ],
        "parameters": [
          {
            "type": "integer",
            "name": "MERCHANT_ID",
            "in": "formData"
          },
          {
            "type": "integer",
            "name": "AMOUNT",
            "in": "formData"
          },
          {
            "type": "integer",
            "name": "intid",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "MERCHANT_ORDER_ID",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "P_EMAIL",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "P_PHONE",
            "in": "formData"
          },
          {
            "type": "integer",
            "name": "CUR_ID",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "payer_account",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "SIGN",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "Deployment scheduled.",
            "schema": {
              "type": "string"
            }
          },
          "500": {
            "description": "Server error."
          }
        }
      }
    },
    "/qiwi-payed": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "$ref": "#/parameters/QiwiPayOpts"
          },
          {
            "type": "string",
            "description": "an authorization header",
            "name": "X-Api-Signature-SHA256",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Deployment scheduled.",
            "schema": {
              "type": "string"
            }
          },
          "500": {
            "description": "Server error."
          }
        }
      }
    },
    "/tryagain": {
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "responses": {
          "200": {
            "description": "Deployment scheduled."
          },
          "500": {
            "description": "Server error."
          }
        }
      }
    }
  },
  "definitions": {
    "QiwiPayOpts": {
      "type": "object",
      "properties": {
        "bill": {
          "type": "object",
          "required": [
            "billId"
          ],
          "properties": {
            "amount": {
              "type": "object",
              "required": [
                "value"
              ],
              "properties": {
                "currency": {
                  "type": "string"
                },
                "value": {
                  "type": "string"
                }
              }
            },
            "billId": {
              "type": "string"
            },
            "creationDateTime": {
              "type": "string"
            },
            "expirationDateTime": {
              "type": "string"
            },
            "siteId": {
              "type": "string"
            },
            "status": {
              "type": "object",
              "required": [
                "value"
              ],
              "properties": {
                "datetime": {
                  "type": "string"
                },
                "value": {
                  "type": "string"
                }
              }
            }
          }
        },
        "version": {
          "type": "string"
        }
      }
    }
  },
  "parameters": {
    "QiwiPayOpts": {
      "name": "qiwiPayOpts",
      "in": "body",
      "schema": {
        "$ref": "#/definitions/QiwiPayOpts"
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "backend",
    "title": "backend",
    "version": "0.0.0"
  },
  "paths": {
    "/notify": {
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "responses": {
          "200": {
            "description": "Deployment scheduled."
          },
          "500": {
            "description": "Server error."
          }
        }
      }
    },
    "/payed": {
      "post": {
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "text/plain"
        ],
        "parameters": [
          {
            "type": "integer",
            "name": "MERCHANT_ID",
            "in": "formData"
          },
          {
            "type": "integer",
            "name": "AMOUNT",
            "in": "formData"
          },
          {
            "type": "integer",
            "name": "intid",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "MERCHANT_ORDER_ID",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "P_EMAIL",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "P_PHONE",
            "in": "formData"
          },
          {
            "type": "integer",
            "name": "CUR_ID",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "payer_account",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "SIGN",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "Deployment scheduled.",
            "schema": {
              "type": "string"
            }
          },
          "500": {
            "description": "Server error."
          }
        }
      }
    },
    "/qiwi-payed": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "qiwiPayOpts",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/QiwiPayOpts"
            }
          },
          {
            "type": "string",
            "description": "an authorization header",
            "name": "X-Api-Signature-SHA256",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Deployment scheduled.",
            "schema": {
              "type": "string"
            }
          },
          "500": {
            "description": "Server error."
          }
        }
      }
    },
    "/tryagain": {
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "responses": {
          "200": {
            "description": "Deployment scheduled."
          },
          "500": {
            "description": "Server error."
          }
        }
      }
    }
  },
  "definitions": {
    "QiwiPayOpts": {
      "type": "object",
      "properties": {
        "bill": {
          "type": "object",
          "required": [
            "billId"
          ],
          "properties": {
            "amount": {
              "type": "object",
              "required": [
                "value"
              ],
              "properties": {
                "currency": {
                  "type": "string"
                },
                "value": {
                  "type": "string"
                }
              }
            },
            "billId": {
              "type": "string"
            },
            "creationDateTime": {
              "type": "string"
            },
            "expirationDateTime": {
              "type": "string"
            },
            "siteId": {
              "type": "string"
            },
            "status": {
              "type": "object",
              "required": [
                "value"
              ],
              "properties": {
                "datetime": {
                  "type": "string"
                },
                "value": {
                  "type": "string"
                }
              }
            }
          }
        },
        "version": {
          "type": "string"
        }
      }
    },
    "QiwiPayOptsBill": {
      "type": "object",
      "required": [
        "billId"
      ],
      "properties": {
        "amount": {
          "type": "object",
          "required": [
            "value"
          ],
          "properties": {
            "currency": {
              "type": "string"
            },
            "value": {
              "type": "string"
            }
          }
        },
        "billId": {
          "type": "string"
        },
        "creationDateTime": {
          "type": "string"
        },
        "expirationDateTime": {
          "type": "string"
        },
        "siteId": {
          "type": "string"
        },
        "status": {
          "type": "object",
          "required": [
            "value"
          ],
          "properties": {
            "datetime": {
              "type": "string"
            },
            "value": {
              "type": "string"
            }
          }
        }
      }
    },
    "QiwiPayOptsBillAmount": {
      "type": "object",
      "required": [
        "value"
      ],
      "properties": {
        "currency": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      }
    },
    "QiwiPayOptsBillStatus": {
      "type": "object",
      "required": [
        "value"
      ],
      "properties": {
        "datetime": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      }
    }
  },
  "parameters": {
    "QiwiPayOpts": {
      "name": "qiwiPayOpts",
      "in": "body",
      "schema": {
        "$ref": "#/definitions/QiwiPayOpts"
      }
    }
  }
}`))
}
