swagger: "3.0"
info:
  title: backend
  description: backend
  version: "0.0.0"



paths:
  /payed:
    post:
      responses:
        200:
          description: Deployment scheduled.
        500:
          description: Server error.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                MERCHANT_ID:          # <!--- form field name
                  type: integer
                AMOUNT:    # <!--- form field name
                  type: float
                intid: # <!--- form field name
                  type: integer
                MERCHANT_ORDER_ID: # <!--- form field name
                  type: string
                P_EMAIL: # <!--- form field name
                  type: string
                P_PHONE: # <!--- form field name
                  type: string
                CUR_ID: # <!--- form field name
                  type: interger
                payer_account: # <!--- form field name
                  type: string
                SIGN:
                  type: string
              required:
                - name
                - email