swagger: "2.0"
info:
  title: backend
  description: backend
  version: "0.0.0"

paths:
  /payed:
    post:
      consumes:
        -  multipart/form-data
      produces:
       -  text/plain
      responses:
        200:
          description: Deployment scheduled.
          schema:
            type: string
        500:
          description: Server error.
      parameters:
      - in: formData
        name: MERCHANT_ID          # <!--- form field name
        type: integer
      - in: formData
        name: AMOUNT    # <!--- form field name
        type: integer
      - in: formData
        name: intid # <!--- form field name
        type: integer
      - in: formData
        name: MERCHANT_ORDER_ID # <!--- form field name
        type: string
      - in: formData
        name: P_EMAIL # <!--- form field name
        type: string
      - in: formData
        name: P_PHONE # <!--- form field name
        type: string
      - in: formData
        name: CUR_ID # <!--- form field name
        type: integer
      - in: formData
        name: payer_account # <!--- form field name
        type: string
      - in: formData
        name: SIGN
        type: string

  /notify:
    post:
      consumes:
        - multipart/form-data
      responses:
        200:
          description: Deployment scheduled.
        500:
          description: Server error.

  /tryagain:
    post:
      consumes:
        - multipart/form-data
      responses:
        200:
          description: Deployment scheduled.
        500:
          description: Server error.