// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostNotifyHandlerFunc turns a function with the right signature into a post notify handler
type PostNotifyHandlerFunc func(PostNotifyParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostNotifyHandlerFunc) Handle(params PostNotifyParams) middleware.Responder {
	return fn(params)
}

// PostNotifyHandler interface for that can handle valid post notify params
type PostNotifyHandler interface {
	Handle(PostNotifyParams) middleware.Responder
}

// NewPostNotify creates a new http.Handler for the post notify operation
func NewPostNotify(ctx *middleware.Context, handler PostNotifyHandler) *PostNotify {
	return &PostNotify{Context: ctx, Handler: handler}
}

/* PostNotify swagger:route POST /notify postNotify

PostNotify post notify API

*/
type PostNotify struct {
	Context *middleware.Context
	Handler PostNotifyHandler
}

func (o *PostNotify) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostNotifyParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
