// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostNotifyOKCode is the HTTP code returned for type PostNotifyOK
const PostNotifyOKCode int = 200

/*PostNotifyOK Deployment scheduled.

swagger:response postNotifyOK
*/
type PostNotifyOK struct {
}

// NewPostNotifyOK creates PostNotifyOK with default headers values
func NewPostNotifyOK() *PostNotifyOK {

	return &PostNotifyOK{}
}

// WriteResponse to the client
func (o *PostNotifyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostNotifyInternalServerErrorCode is the HTTP code returned for type PostNotifyInternalServerError
const PostNotifyInternalServerErrorCode int = 500

/*PostNotifyInternalServerError Server error.

swagger:response postNotifyInternalServerError
*/
type PostNotifyInternalServerError struct {
}

// NewPostNotifyInternalServerError creates PostNotifyInternalServerError with default headers values
func NewPostNotifyInternalServerError() *PostNotifyInternalServerError {

	return &PostNotifyInternalServerError{}
}

// WriteResponse to the client
func (o *PostNotifyInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
