// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"

	"backend-vpn/internal/api/models"
)

// NewPostQiwiPayedParams creates a new PostQiwiPayedParams object
//
// There are no default values defined in the spec.
func NewPostQiwiPayedParams() PostQiwiPayedParams {

	return PostQiwiPayedParams{}
}

// PostQiwiPayedParams contains all the bound params for the post qiwi payed operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostQiwiPayed
type PostQiwiPayedParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*an authorization header
	  Required: true
	  In: header
	*/
	XAPISignatureSHA256 string
	/*
	  In: body
	*/
	QiwiPayOpts *models.QiwiPayOpts
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostQiwiPayedParams() beforehand.
func (o *PostQiwiPayedParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := o.bindXAPISignatureSHA256(r.Header[http.CanonicalHeaderKey("X-Api-Signature-SHA256")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.QiwiPayOpts
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("qiwiPayOpts", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(context.Background())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.QiwiPayOpts = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindXAPISignatureSHA256 binds and validates parameter XAPISignatureSHA256 from header.
func (o *PostQiwiPayedParams) bindXAPISignatureSHA256(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("X-Api-Signature-SHA256", "header", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("X-Api-Signature-SHA256", "header", raw); err != nil {
		return err
	}
	o.XAPISignatureSHA256 = raw

	return nil
}
