// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostPayedOKCode is the HTTP code returned for type PostPayedOK
const PostPayedOKCode int = 200

/*PostPayedOK Deployment scheduled.

swagger:response postPayedOK
*/
type PostPayedOK struct {
}

// NewPostPayedOK creates PostPayedOK with default headers values
func NewPostPayedOK() *PostPayedOK {

	return &PostPayedOK{}
}

// WriteResponse to the client
func (o *PostPayedOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostPayedInternalServerErrorCode is the HTTP code returned for type PostPayedInternalServerError
const PostPayedInternalServerErrorCode int = 500

/*PostPayedInternalServerError Server error.

swagger:response postPayedInternalServerError
*/
type PostPayedInternalServerError struct {
}

// NewPostPayedInternalServerError creates PostPayedInternalServerError with default headers values
func NewPostPayedInternalServerError() *PostPayedInternalServerError {

	return &PostPayedInternalServerError{}
}

// WriteResponse to the client
func (o *PostPayedInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
