// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostTryagainOKCode is the HTTP code returned for type PostTryagainOK
const PostTryagainOKCode int = 200

/*PostTryagainOK Deployment scheduled.

swagger:response postTryagainOK
*/
type PostTryagainOK struct {
}

// NewPostTryagainOK creates PostTryagainOK with default headers values
func NewPostTryagainOK() *PostTryagainOK {

	return &PostTryagainOK{}
}

// WriteResponse to the client
func (o *PostTryagainOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostTryagainInternalServerErrorCode is the HTTP code returned for type PostTryagainInternalServerError
const PostTryagainInternalServerErrorCode int = 500

/*PostTryagainInternalServerError Server error.

swagger:response postTryagainInternalServerError
*/
type PostTryagainInternalServerError struct {
}

// NewPostTryagainInternalServerError creates PostTryagainInternalServerError with default headers values
func NewPostTryagainInternalServerError() *PostTryagainInternalServerError {

	return &PostTryagainInternalServerError{}
}

// WriteResponse to the client
func (o *PostTryagainInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
