// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostQiwiPayedOKCode is the HTTP code returned for type PostQiwiPayedOK
const PostQiwiPayedOKCode int = 200

/*PostQiwiPayedOK Deployment scheduled.

swagger:response postQiwiPayedOK
*/
type PostQiwiPayedOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostQiwiPayedOK creates PostQiwiPayedOK with default headers values
func NewPostQiwiPayedOK() *PostQiwiPayedOK {

	return &PostQiwiPayedOK{}
}

// WithPayload adds the payload to the post qiwi payed o k response
func (o *PostQiwiPayedOK) WithPayload(payload string) *PostQiwiPayedOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post qiwi payed o k response
func (o *PostQiwiPayedOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostQiwiPayedOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostQiwiPayedInternalServerErrorCode is the HTTP code returned for type PostQiwiPayedInternalServerError
const PostQiwiPayedInternalServerErrorCode int = 500

/*PostQiwiPayedInternalServerError Server error.

swagger:response postQiwiPayedInternalServerError
*/
type PostQiwiPayedInternalServerError struct {
}

// NewPostQiwiPayedInternalServerError creates PostQiwiPayedInternalServerError with default headers values
func NewPostQiwiPayedInternalServerError() *PostQiwiPayedInternalServerError {

	return &PostQiwiPayedInternalServerError{}
}

// WriteResponse to the client
func (o *PostQiwiPayedInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
