// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostPayedOKCode is the HTTP code returned for type PostPayedOK
const PostPayedOKCode int = 200

/*PostPayedOK Deployment scheduled.

swagger:response postPayedOK
*/
type PostPayedOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostPayedOK creates PostPayedOK with default headers values
func NewPostPayedOK() *PostPayedOK {

	return &PostPayedOK{}
}

// WithPayload adds the payload to the post payed o k response
func (o *PostPayedOK) WithPayload(payload string) *PostPayedOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post payed o k response
func (o *PostPayedOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostPayedOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostPayedInternalServerErrorCode is the HTTP code returned for type PostPayedInternalServerError
const PostPayedInternalServerErrorCode int = 500

/*PostPayedInternalServerError Server error.

swagger:response postPayedInternalServerError
*/
type PostPayedInternalServerError struct {
}

// NewPostPayedInternalServerError creates PostPayedInternalServerError with default headers values
func NewPostPayedInternalServerError() *PostPayedInternalServerError {

	return &PostPayedInternalServerError{}
}

// WriteResponse to the client
func (o *PostPayedInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
